
export const galleryImages = [
    {id: 1, img: '/assets/img/gallery/cake-gallery-1.jpg', alt: 'gal1'},
    {id: 2, img: '/assets/img/gallery/cake-gallery-2.jpg', alt: 'gal2'},
    {id: 3, img: '/assets/img/gallery/cake-gallery-3.jpg', alt: 'gal3'},
    {id: 4, img: '/assets/img/gallery/cake-gallery-4.jpg', alt: 'gal4'},
    {id: 5, img: '/assets/img/gallery/cake-gallery-5.jpg', alt: 'gal5'},
    {id: 6, img: '/assets/img/gallery/cake-gallery-6.jpg', alt: 'gal6'},
    {id: 7, img: '/assets/img/gallery/cake-gallery-7.jpg', alt: 'gal7'},
    {id: 8, img: '/assets/img/gallery/cake-gallery-8.jpg', alt: 'gal8'},
    {id: 9, img: '/assets/img/gallery/cake-gallery-9.jpg', alt: 'gal9'},
    {id: 10, img: '/assets/img/gallery/cake-gallery-10.jpg', alt: 'gal10'},
    {id: 11, img: '/assets/img/gallery/cake-gallery-11.jpg', alt: 'gal11'},
    {id: 12, img: '/assets/img/gallery/cake-gallery-12.jpg', alt: 'gal12'},
    {id: 13, img: '/assets/img/gallery/cake-gallery-13.jpg', alt: 'gal13'},
    {id: 14, img: '/assets/img/gallery/cake-gallery-14.jpg', alt: 'gal14'},
    {id: 15, img: '/assets/img/gallery/cake-gallery-15.jpg', alt: 'gal15'},
    {id: 16, img: '/assets/img/gallery/cake-gallery-16.jpg', alt: 'gal16'},
    {id: 17, img: '/assets/img/gallery/cake-gallery-17.jpg', alt: 'gal17'},
]